services:
  server:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ${HOOGLE_ROOT_DIR}/.hoogle:${HOOGLE_ROOT_DIR}/.hoogle
    environment:
      - HOOGLE_ROOT_DIR=${HOOGLE_ROOT_DIR}
    develop:
      watch:
        - action: rebuild
          path: ./api
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    develop:
      watch:
        - action: rebuild
          path: ./frontend

networks:
  bridge:
    driver: bridge

